# Generated by Django 3.1.4 on 2020-12-11 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField(auto_now_add=True, verbose_name='fecha de pago')),
                ('documentoIdentificacionArrendatario', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='id arrendatario')),
                ('codigoInmueble', models.TextField(blank=True, verbose_name='codigo inmueble')),
                ('valorPagado', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
