# Generated by Django 3.1.4 on 2020-12-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='documentoIdentificacionArrendatario',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id arrendatario'),
        ),
    ]
